// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Upstart13.BeerApp.Entities
{
    public partial class MethodType
    {
        public MethodType()
        {
            Method = new HashSet<Method>();
        }

        public int MethodTypeId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Method> Method { get; set; }
    }
}