// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Upstart13.BeerApp.Entities
{
    public partial class Method
    {
        public int MethodId { get; set; }
        public int MethodTypeId { get; set; }
        public int BeerId { get; set; }
        public string TemperatureUnit { get; set; }
        public int? TemperatureValue { get; set; }
        public int? Duration { get; set; }

        public virtual Beer Beer { get; set; }
        public virtual MethodType MethodType { get; set; }
    }
}