// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Upstart13.BeerApp.Entities
{
    public partial class VolumeType
    {
        public VolumeType()
        {
            Volume = new HashSet<Volume>();
        }

        public int VolumeTypeId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Volume> Volume { get; set; }
    }
}