// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Upstart13.BeerApp.Entities
{
    public partial class Volume
    {
        public int VolumeId { get; set; }
        public int VolumeTypeId { get; set; }
        public int BeerId { get; set; }
        public string VolumeUnit { get; set; }
        public int? VolumeValue { get; set; }

        public virtual Beer Beer { get; set; }
        public virtual VolumeType VolumeType { get; set; }
    }
}